version: "3.7"

services:

  flask:
    build: ./
    container_name: template_flask
    # restart: always
    environment:
      - APP_NAME=FlaskApp
    expose:
      - 5000

  nginx:
    build: ./nginx
    container_name: template_nginx
    # restart: always
    ports:
      - "80:80"

    depends_on:
      - flask